### ISSUE TITLE
FR: Custom notification based on entry field

### ISSUE THREAD

**Issue by davorpeic** [taylordaughtry/Craft-Brief#10]
Hi Taylor, 

great plugin, and I see you are very active with FR, we really appreciate that.

I know I'm pushing the limits maybe, I have a registration form, and would like to send a copy of "thanks for subscribing" to the user that created the entry (guest). Is there a workaround I can do with latest 1.5.0 version?

Thanks

**Comment by taylordaughtry** [comment]
Hey! No problem; thanks for using Brief!

That's a conversation I'd like to have; it's essentially making Brief more than what it was currently meant to be. Not that I'm opposed to it, but the appeal of Brief is in its simplicity: user notifications, and nothing more.

I'd consider adding this feature; it wouldn't be too big of a deal. Can you expand on how you'd use that feature, if Brief had it? (I'm basically looking for context as to the use-case.)

**Comment by davorpeic** [comment]
Yeah, I totally get you :)

Basically the person that fills the form (new entry) leaves his email in one of the fields. I would like to be able to send to that field (email) also a copy of the notification in a form of "Thank you for the submission".

Not sure if this could complicate too much of a things, but maybe adding 2 new settings in Brief that would be marked as "custom" notification where you could define which field is the email and the next one which template would you use for that custom notification.. and then in that template you could send entire entry object so we could access that entry fields.

Maybe I'm complicating stuff, and I hope someone else could post their use-cases so you could find the best way (if) to accomplish this :)

thanks
davor

**Comment by taylordaughtry** [comment]
That's totally within the realm of possibility. I'm actually in the process of adding something like this to Brief in the next release: custom email templates. You'd basically tell Brief which template you'd like to use for different types of notifications, and Brief will fill in those templates with the relevant data. 

As for the form notifications, that'll be added in the next release, as well. It'll use a hidden action input:

`<input type="hidden" name="action" value="brief/notifySubmitter">`

I'm still working on how to accommodate developers who can't add another hidden action input. You can't have two action inputs, so I'd have to add functionality for Brief to run its code, then call the other controller actions. Simple, but I'm not sure I want something like that in a plugin that's trying to stay lean.

Stay tuned; I'll see about pushing that form notification feature in the next day or so!
