### ISSUE TITLE
Add an optional reply-to option

### ISSUE THREAD

**Issue by dowadidi** [taylordaughtry/Craft-Brief#13]
It would be nice to have the option to set an optional reply-to email address. Eg. using a {{field}} value if it contains a valid email address.

**Comment by taylordaughtry** [comment]
Can you explain a little more about what you're looking for here? I've added a 'replyTo' setting in the upcoming release (sometime this week). Would that work for your needs?

**Comment by taylordaughtry** [comment]
For those interested, this has now been added in the master branch. You can add a `replyTo` address by specifying one in the Settings. If you don't have it, Brief will carry on as normal.
