### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by outline4** [taylordaughtry/Craft-Brief#15]
After I've uploaded the plugin I navigated to the plugin section to find this error: 
Parse error: syntax error, unexpected '.', expecting ',' or ';' in …/craft/plugins/brief/BriefPlugin.php on line 13

Cheers
Stefan

**Comment by tosegard** [comment]
I may be experiencing the same error, whenever the 'brief' folder is uploaded to my 'plugins' folder my server won't load the settings>plugins page.

**Comment by michaeldavidtodd** [comment]
**This fixed it for me**
Line 13: change to the following:
`private $feedUrl = 'https://raw.githubusercontent.com/taylordaughtry/Craft-Brief/master/brief/releases.json';`
Line 14: remove

**Comment by taylordaughtry** [comment]
Thanks for the heads up! Looks like a recent version of Craft has a problem with concatenation of plugin settings. Should be good to go!
