### ISSUE TITLE
Error when using {{ title }} in the email subject input

### ISSUE THREAD

**Issue by michaeldavidtodd** [taylordaughtry/Craft-Brief#16]
When setting this up, if I enter anything with curly brackets, such as {{ title }}, into the email subject input, it throws an error, which breaks the entire /plugins page. I'm having to restore my database from a backup to clear it out in order to reset the plugin and try again. Deleting the plug and replacing it with a fresh copy doesn't clear the error.

Running Craft v. 2.6.2944

PHP notice: Array to string conversion

**Comment by taylordaughtry** [comment]
I'm checking this out now!

**Comment by taylordaughtry** [comment]
@michaeldavidtodd Just push a commit to `master` that should fix this. Looks like Craft was trying to parse the twig tags on save after a recent update. I encoded the subject (it should've been encoded anyway), and it resolved the issue. Double-checked parsing and all seems to be well; let me know if you're still experiencing the issue.

Thanks for using Brief!

**Comment by michaeldavidtodd** [comment]
I just realized I never replied to this! Thank you so much, @taylordaughtry! I love this plugin and it's been really really helpful. I reported another bug (or maybe it's a problem on my end). Let me know if you have any thoughts. I appreciate any help.

Thanks, again.
