### ISSUE TITLE
Add 'API' like functionality

### ISSUE THREAD

**Issue by EternalBlack** [taylordaughtry/Craft-Brief#20]
I would love to see API functionality like being able as a logged in user to fetch new events via ajax in a polling interval and displaying those as pop-ups on site (to moderators/administrators. Something like "New post awaiting moderation").
I still have to take a look at the code to see if it would be possible with with the infrastructure of the plugin. If it's fire-and-forget (which I unfortunately assume it is) it probably wouldn't be possible, but if it's already stored somewhere it should be 'easily' achievable.

**Comment by taylordaughtry** [comment]
That sounds like great functionality, but that would be firmly in the realm of a separate plugin. Brief's only concerned with Email Notifications, and relies on Craft's native `EmailService` to notify users.

That said, it's a good idea for a plugin. All you'd really need to do is write a plugin that stores event information, and provides it in `JSON` format to an endpoint. (Heck, you might even be able to solve this with the JSON API, or something else.)
