### ISSUE TITLE
Add ability to check if the item triggering notification is related to the user

### ISSUE THREAD

**Issue by aladrach** [taylordaughtry/Craft-Brief#21]
I'd love a way to check to see if the item that is triggering the notification is related to the user. I've got a simple discussion community set up and would love to be able to trigger notifications based on whether it's from a topic that the user has posted in.

**Comment by taylordaughtry** [comment]
@aladrach That's an interesting use-case, however I think it might be a _bit_ specialized to include in Brief. (My goal is to keep the plugin streamlined.)

However, it is a good idea for some sort of add-on to Brief. You'd need to somehow setup a way to relate users to content, which could be tricky (and potentially a significant performance issue.)

Let me know if you want to discuss this further; I'd be glad to help. (Just reopen this issue.)
