### ISSUE TITLE
Add ability to notify on saved but not enabled entries too

### ISSUE THREAD

**Issue by Saboteur777** [taylordaughtry/Craft-Brief#22]
I am using P&T's GuestEntry plugin to create disabled (="not published") Quote entries whenever a visitor asks a quote. These entries are created successfully but notification is only sent if they are created as enabled. Is it possible to send notifications for disabled entries?

**Comment by taylordaughtry** [comment]
@Saboteur777 Brief is actually explicitly checking that entries aren't disabled before sending an email. Thinking about it, it makes more sense to make this an optional setting, because of cases like yours. (I've done the same thing for clients in the past.)

I'm working on this now!

**Comment by taylordaughtry** [comment]
@Saboteur777 This is now added in the Master branch. Thanks for using Brief!

**Comment by Saboteur777** [comment]
Thank you! 😻
