### ISSUE TITLE
Could not instantiate mail function when using craftman Docker-based tool

### ISSUE THREAD

**Issue by Saboteur777** [taylordaughtry/Craft-Brief#23]
I got the following error: 

Craft\Exception
E-mail error: Could not instantiate mail function

I am using craftman (https://github.com/gabrielmoreira/craftman), my Craft site is now running in a Docker container. 

/var/www/craft/app/services/EmailService.php(475)
```
if ($errorMessage)
466             {
467                 // Fire an 'onSendEmailError' event
468                 $this->onSendEmailError(new Event($this, array(
469                     'user' => $user,
470                     'emailModel' => $emailModel,
471                     'variables' => $variables,
472                     'error' => $errorMessage,
473                 )));
474 
475                 throw new Exception(Craft::t('Email error: {error}', array('error' => $errorMessage)));
476             }
477 
```

[Craft_Exception.pdf](https://github.com/taylordaughtry/Craft-Brief/files/614172/Craft_Exception.pdf)

**Comment by taylordaughtry** [comment]
@Saboteur777 This sounds like an issue with your Craft install or with the Craftman plugin; I'm not immediately sure if this is coming from Brief. (Brief relies on Craft's native `EmailService` to send.)

If you're still seeing this in the future, feel free to reopen this issue with more information, and I'll check it out. Thanks for using Brief!

**Comment by Saboteur777** [comment]
@taylordaughtry Yeah, it is, thank you for looking into it! Opened another issue here: https://github.com/angusfretwell/craftsman/issues/50
