### ISSUE TITLE
Improper dynamic data in email body

### ISSUE THREAD

**Issue by hybridinteractive** [taylordaughtry/Craft-Brief#24]
I love this plugin but the email body says:

Hey, there! There's been an update or addition to the News Section

Although the Subject says "Signup - Listings Signup". 

Shouldn't the body say "Hey, there! There's been an update or addition to the Signup - Listings Signup"?

**Comment by taylordaughtry** [comment]
@encryptdesigns I can't seem to replicate this locally. If you're still seeing this issue, feel free to reopen this and provide a bit more information on what's happening, and I'd be glad to take a look. Thanks for using Brief!
