### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by brianandgarcia** [taylordaughtry/Craft-Brief#27]
Get notified when an entry is edited. 

I am using Craft as a project / client manager. Entries are "Clients" and are updated periodically.

**Comment by taylordaughtry** [comment]
Hey! Brief actually does that already; if an entry is created _or_ updated, users with proper permissions (based on User Groups) will get a notification about it. If you're not seeing that functionality, definitely reopen this and I'd be glad to take a look. Thanks!
