### ISSUE TITLE
Update to 2.0.1 breaks admin/settings

### ISSUE THREAD

**Issue by Saboteur777** [taylordaughtry/Craft-Brief#30]
Internal error
"Array to string conversion"

`GET https://webmenedzser.hu/admin/settings 500 ()`
`craft.js:5 Uncaught ReferenceError: Craft is not defined`
`    at craft.js:5`
`    at craft.js:17607`
`(anonymous) @ craft.js:5`
`(anonymous) @ craft.js:17607`
`cp.js:7 Uncaught ReferenceError: Craft is not defined`
`    at cp.js:7`
`    at cp.js:1484`
`(anonymous) @ cp.js:7`
`(anonymous) @ cp.js:1484`
`settings.js:4 Uncaught ReferenceError: Craft is not defined`
`    at settings.js:4`
`    at settings.js:241`
`(anonymous) @ settings.js:4`
`(anonymous) @ settings.js:241`
`settings:52 Uncaught ReferenceError: Craft is not defined`
`    at settings:52`

**Comment by taylordaughtry** [comment]
Hey! Not sure if you're still experiencing this issue, but I think it might be something in your local install; It's fully function on 2.6 on this end.

Let me know if you're having trouble with it! Thanks.

**Comment by Saboteur777** [comment]
Hey! Thanks for the headsup! It is still there, the relevant log from `craft/storage/runtime/logs/`: 

******************************************************************************************************
2017/08/24 07:33:54 [error] [php] Array to string conversion (/web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/7a/7a434b7933e3e6907c25ce612c8f64de297ae6e358064f541763eb87eca1c044.php:68)
Stack trace:
#0 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_754affa5b4b42c27be2e65fc7996a51711fae66f17d692c95801408f136777cc->displayWithErrorHandling()
#1 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_754affa5b4b42c27be2e65fc7996a51711fae66f17d692c95801408f136777cc->displayWithErrorHandling()
#2 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/f0/f065301543f4456ce560069889e4cf4ec40fc504bbb3b3b3c9696670f703fd56.php(245): __TwigTemplate_754affa5b4b42c27be2e65fc7996a51711fae66f17d692c95801408f136777cc->display()
#3 unknown(0): __TwigTemplate_7562144b07fb4e3f7fe04a154102e0766f5cb706cfed2ddadca411d1d133a1d9->gettext()
#4 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(688): call_user_func_array()
#5 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(64): __TwigTemplate_7562144b07fb4e3f7fe04a154102e0766f5cb706cfed2ddadca411d1d133a1d9->getAttribute()
#6 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/f0/f065301543f4456ce560069889e4cf4ec40fc504bbb3b3b3c9696670f703fd56.php(772): __TwigTemplate_7562144b07fb4e3f7fe04a154102e0766f5cb706cfed2ddadca411d1d133a1d9->getAttribute()
#7 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/14/14be3827bf0f6f384f82182faa7328412b566fdcad9d2f2495b318a61d8a2551.php(31): __TwigTemplate_7562144b07fb4e3f7fe04a154102e0766f5cb706cfed2ddadca411d1d133a1d9->gettextField()
#8 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_accbeb7ed237206a6c51e637ddf74f0a7a06c66b1dfa28136ec454a5e49a847e->doDisplay()
#9 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_accbeb7ed237206a6c51e637ddf74f0a7a06c66b1dfa28136ec454a5e49a847e->displayWithErrorHandling()
#10 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_accbeb7ed237206a6c51e637ddf74f0a7a06c66b1dfa28136ec454a5e49a847e->displayWithErrorHandling()
#11 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(411): __TwigTemplate_accbeb7ed237206a6c51e637ddf74f0a7a06c66b1dfa28136ec454a5e49a847e->display()
#12 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Environment.php(362): __TwigTemplate_accbeb7ed237206a6c51e637ddf74f0a7a06c66b1dfa28136ec454a5e49a847e->render()
#13 /web/styluskoromszalon/webmenedzser_craft/app/services/TemplatesService.php(256): Craft\TwigEnvironment->render()
#14 /web/styluskoromszalon/webmenedzser_craft/plugins/brief/BriefPlugin.php(66): Craft\TemplatesService->render()
#15 /web/styluskoromszalon/webmenedzser_craft/app/etc/plugins/BasePlugin.php(125): Craft\BriefPlugin->getSettingsHtml()
#16 /web/styluskoromszalon/webmenedzser_craft/app/variables/CpVariable.php(162): Craft\BriefPlugin->hasSettings()
#17 unknown(0): Craft\CpVariable->settings()
#18 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(688): call_user_func_array()
#19 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(64): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->getAttribute()
#20 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/aa/aabf787e5001ecbf438d6b7efff1bb74c3ef1fe60fc32f5eac1d0464655dc38b.php(42): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->getAttribute()
#21 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->block_content()
#22 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/2b/2b88bbb17e79508991fba255d9cc2a26de812b9b0c6f64eb878dc7a63be65acb.php(740): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->displayBlock()
#23 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->block_body()
#24 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/52/527abfc5a5d10870fcbef39559b5abb349e64df32e6101e009f83df96b0ac777.php(45): __TwigTemplate_5ee13f4cc46b5329b2946eb1a320a582b57d4502aff47e0f3c86c348a002aa95->displayBlock()
#25 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_5ee13f4cc46b5329b2946eb1a320a582b57d4502aff47e0f3c86c348a002aa95->doDisplay()
#26 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_5ee13f4cc46b5329b2946eb1a320a582b57d4502aff47e0f3c86c348a002aa95->displayWithErrorHandling()
#27 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_5ee13f4cc46b5329b2946eb1a320a582b57d4502aff47e0f3c86c348a002aa95->displayWithErrorHandling()
#28 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/3c/3cbbba0e1fab381f1635e4d542e700f81ffe65eae717911f29ac2a5bbf203171.php(131): __TwigTemplate_5ee13f4cc46b5329b2946eb1a320a582b57d4502aff47e0f3c86c348a002aa95->display()
#29 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_a2a567c51e6deb335daf1d61311d39e0b48725b737f84fa6805731bc77a0c162->doDisplay()
#30 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_a2a567c51e6deb335daf1d61311d39e0b48725b737f84fa6805731bc77a0c162->displayWithErrorHandling()
#31 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_a2a567c51e6deb335daf1d61311d39e0b48725b737f84fa6805731bc77a0c162->displayWithErrorHandling()
#32 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/2b/2b88bbb17e79508991fba255d9cc2a26de812b9b0c6f64eb878dc7a63be65acb.php(169): __TwigTemplate_a2a567c51e6deb335daf1d61311d39e0b48725b737f84fa6805731bc77a0c162->display()
#33 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->doDisplay()
#34 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->displayWithErrorHandling()
#35 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->displayWithErrorHandling()
#36 /web/styluskoromszalon/webmenedzser_craft/storage/runtime/compiled_templates/aa/aabf787e5001ecbf438d6b7efff1bb74c3ef1fe60fc32f5eac1d0464655dc38b.php(33): __TwigTemplate_f62bd5cf5024c3f922cc51c0e049748b7bea52fc0d5f88e46e26261e357ce356->display()
#37 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->doDisplay()
#38 /web/styluskoromszalon/webmenedzser_craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->displayWithErrorHandling()
#39 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(403): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->displayWithErrorHandling()
#40 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Template.php(411): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->display()
#41 /web/styluskoromszalon/webmenedzser_craft/app/vendor/twig/twig/lib/Twig/Environment.php(362): __TwigTemplate_41967a5c55ddf4c3f95e74d4152cb36ef6993245cc521c3c1ddbbf4ff72470dd->render()
#42 /web/styluskoromszalon/webmenedzser_craft/app/services/TemplatesService.php(256): Craft\TwigEnvironment->render()
#43 /web/styluskoromszalon/webmenedzser_craft/app/controllers/BaseController.php(74): Craft\TemplatesService->render()
#44 /web/styluskoromszalon/webmenedzser_craft/app/controllers/SystemSettingsController.php(53): Craft\SystemSettingsController->renderTemplate()
#45 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/actions/CInlineAction.php(49): Craft\SystemSettingsController->actionSettingsIndex()
#46 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#47 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/CController.php(286): Craft\SystemSettingsController->runAction()
#48 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/CController.php(265): Craft\SystemSettingsController->runActionWithFilters()
#49 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/CWebApplication.php(282): Craft\SystemSettingsController->run()
#50 /web/styluskoromszalon/webmenedzser_craft/app/framework/web/CWebApplication.php(141): Craft\WebApp->runController()
#51 /web/styluskoromszalon/webmenedzser_craft/app/etc/web/WebApp.php(290): Craft\WebApp->processRequest()
#52 /web/styluskoromszalon/webmenedzser_craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#53 /web/styluskoromszalon/webmenedzser_craft/app/index.php(62): Craft\WebApp->run()
#54 /web/styluskoromszalon/webmenedzser.hu/index.php(19): require_once()
REQUEST_URI=/admin/settings

It might be the local install: what should I check?
