### ISSUE TITLE
Where do I Select a Section?

### ISSUE THREAD

**Issue by MichaelLotriet** [taylordaughtry/Craft-Brief#32]
Hi,

I am trying to use your plugin to notify users when an entry is saved in a specific section.

In your documentation, it says "In Brief's settings, specify which section you'd like to be notified about. For example, if you'd like to be notified when an entry is updated or deleted in the 'News' section, you'd select News from the dropdown."

But I seen no dropdown, as shown below:
![screen shot 2017-07-21 at 12 08 25 pm](https://user-images.githubusercontent.com/7499927/28459355-683126a4-6e0d-11e7-8ba6-b17fc70fad96.png)

Is there any thing I'm missing?

Thank You

**Comment by taylordaughtry** [comment]
Hey! This is actually a case where the docs need to be updated; you can now set permissions directly on User Groups, and on a per-section basis.

If you check your user groups, you should be Brief permissions in there.

Thanks for using Brief! Let me know if you have any other questions; I'd be glad to help out.

**Comment by MichaelLotriet** [comment]
Oh. The plugin works perfectly.

Thank You!
