### ISSUE TITLE
Include user info in body?

### ISSUE THREAD

**Issue by ghost** [taylordaughtry/Craft-Brief#33]
Hi There!

Great plugin!
I want to include the name of the receiver into the e-mail body. 

I tried to manage that with the BriefService.php. But still no succes.
Can you help me, of handle me an example?

When i try to read the user's name, it keeps saying the CP admin name.

Thank you!

Greetings,
Bodil Seekles
Bubblefish Interactive

**Comment by taylordaughtry** [comment]
If you pull the latest commits, you should have access to the `entry` and `user` models in both the subject and body of the notifications. 

Thanks for using Brief!
