### ISSUE TITLE
Error in settings if no groups exist

### ISSUE THREAD

**Issue by davorpeic** [taylordaughtry/Craft-Brief#9]
Hi,

if I don't have any groups created, function getGroups() returns error

https://www.dropbox.com/s/hhzvbcw91itm7ht/Screenshot%202016-02-09%2023.42.25.png?dl=0

After that is needed to disable the plugin in craft_plugins table and then create group and activate the plugin.

thanks
davor

**Comment by taylordaughtry** [comment]
Thanks for pointing that out! Let me know if you have any other issues.
